# Minecraft Properties
# For changes in new Minecraft, see https://docs.neoforged.net/primer/docs/
java_version=25
minecraft_version=26.1
supported_minecraft_versions=>=26.1

# Mod Properties
mod_version=1.0.0+26.1
maven_group=se.icus.mag
archives_base_name=vine-cork

# Fabric
# Check for latest at https://fabricmc.net/develop
loader_version=0.19.3
loom_version=1.17.16
fabric_api_version=0.145.1+26.1

# Spotless
# Check for latest at https://plugins.gradle.org/plugin/com.diffplug.spotless
spotless_version=7.2.1
# Check for latest at https://plugins.gradle.org/plugin/com.palantir.java-format-spotless
spotless_palantir_version=2.72.0
# Check for latest at https://github.com/google/gson/releases
spotless_gson_version=2.13.1
# Check for latest at https://groovy.jfrog.io/ui/native/plugins-release/org/codehaus/groovy/groovy-eclipse-integration/4.9.0
spotless_greclipse_version=4.27

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
